# Generated by Django 4.0 on 2021-12-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('balance', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
